# Generated by Django 3.0.6 on 2020-05-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=20)),
                ('ppg', models.CharField(max_length=5)),
                ('rpg', models.CharField(max_length=5)),
                ('apg', models.CharField(max_length=5)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
