# Generated by Django 3.0.6 on 2020-05-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20200520_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=50)),
                ('team_abr', models.CharField(max_length=10)),
            ],
        ),
    ]
