# Generated by Django 3.0.6 on 2020-05-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='d'),
            preserve_default=False,
        ),
    ]
