# Generated by Django 3.0.6 on 2020-06-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='first_season',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last_season',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
    ]
